### ISSUE TITLE
Deleting sprites to reduce lag may crash the game

### ISSUE THREAD

**Issue by Xplode111** [HBroHei/NSMRWii#12]
Heya, I've been trying to randomize NSMBW many times, but when I'm going to play the levels, something crashes the game. I've looked for the reasons why my game crashes every 2 levels (average) because something crashes while loading it, and I think it is caused by a generation error, because when I randomize the Stage folder, a message like this pops up like 15 times aprox on the terminal (but obviusly with different values): **WARNING: Cannot remove sprite [118, 4704, 640, b'\x00\x00\x00\x00\x00\x01', 0, b'\x00']**
Could someone help me, please?

**Comment by HBroHei** [comment]
Can you share the config.json that you used here so that I can replicate the crash? Thanks.

**Comment by Xplode111** [comment]
The problem is not in the randomizer, the randomizer goes well (with the warnings I said previously) and is not what is crashing. The problem occurs while I emulate NSMBW with the randomized Stage folder (or a Riivolution patch with the changes made with the randomizer). 
While I'm playing NSMBW in Dolphin with the randomized Stage folder with your randomizer, eventually the game pops up like 4-5 errors in hexadecimal code (it can happen before starting a Stage or even in the middle of a stage, but never in menus or in the world (basically before entering a stage)) and it crashes. In terms of stages and pure trial and error, the average is 2 stages before the game crashes.
I'm pretty sure that the config.json file is not the problem, because I tried like more than 20 times with completely different config.json files and the randomizer creates the Stage_Shuffled folder correctly, but when the Stage_Shuffled folder is created, that is when the terminal notificates the errors like: **WARNING: Cannot remove sprite [118, 4704, 640, b'\x00\x00\x00\x00\x00\x01', 0, b'\x00']**, I try playing the game and it still crashes while playing.
I can give you the last config.json I used for randomizing the folder, but as I said previously, I don't think the problem is on the file config.json.
I think the problem is about those warnings that appear every time I randomize the folder with every config.json file I create.
I'm sorry if you misunderstood the situation.
Could you help me with that? Thanks.

**Comment by HBroHei** [comment]
Thanks for providing more information about the crash. I can confirm it would happen in any seed.

After some playtesting, it seems that the "Reduce Lag" option would cause this crash.

I have already identified the problematic part of the source code, but I will be busy tomorrow and unable to fix the bug, so I apologise that the earliest date that I can release a patch for this will be on Wednesday.

If you want a temporary fix, please disable the "Reduce Lag" option when generating the config.json file. Since you are playing on dolphin, as long as your computer is not too underpowered, the gameplay should be fine. (Except for the original 9-7, where it lags a bit)

Thanks again for reporting this bug!

**Comment by Xplode111** [comment]
ok, then I'll disable the Reduce Lag option meanwhile. I'll let you know if I find another bug. Thanks! ^^
