### ISSUE TITLE
Nonsense death

### ISSUE THREAD

**Issue by Xplode111** [HBroHei/NSMRWii#14]
Heya, I've been playing well the first 6 worlds until 6-Castle, which was replaced with 9-3. It had not any issues until I tried to get to the second coin. As soon as you enter the pipe and get to that cloud part, you die instantly.
I uploaded another clip so you can see the bug.
I also added the config.json file I used hoping it helps to find the error. Thanks!
https://www.mediafire.com/file/6yr4mjnfvq7p3lq/clip2.mp4/file
[config.json](https://github.com/HBroHei/NSMRWii/files/15475520/config.json)

I were at stage 8-3 randomized with the same config.json file and something strange happened too. It was replaced by 5-2. At first everything was fine, until I entered the first pipe. Some errors with hexadecimal values again started to pop up (it happened too when I got to the third coin), I accepted all of them and eventually they let me to enter to the stage. Then I found that the original magma waves were there, but "glitched" (they appeared and worked fine but their color was replaced by a grayscale). This is an error or the waves are actually hardcoded from the 8-3 stage?

**Comment by HBroHei** [comment]
For 6-Caastle: This is likely caused by a hardcoded feature mentioned in https://horizon.miraheze.org/wiki/Level_Names_and_Features#Hardcoded_Level_Features

I will be redoing the generator's Map "Level skip randomisation" section to include more features. Until then, you can replace your config.json with the one 
[here](https://github.com/user-attachments/files/15528893/config.json). You need to run the randomiser script again, but it will make 6-Castle stays at original 6-Castle spot.

For 8-3: The game hardcoded the lava waves in there, also mentioned in the above link. This should not affect "normal" gameplay after getting past the error messages. Again, I will be redoing the generator's Map "Level skipping randomisation" section, son please wait for that.

Thanks for mentioning this issue to me

**Comment by HBroHei** [comment]
The generator now includes options for skipping map randomisation for 6-Castle and 8-3. Thank you again for bringing this up to me.
